### ISSUE TITLE
Setting Items

### ISSUE THREAD

**Issue by josephlewis42** [connectordb/duck#1]
Along with a Get() duck should have Set([]interface{}, value) for its objects.

**Comment by dkumor** [comment]
Sounds reasonable. Here's the idea:
```go
duck.Set(val, setto interface{}) (ok bool)
duck.SetItem(val, element, setto interface{}) (ok bool)
```

**Comment by josephlewis42** [comment]
What about sub-sub objects? I don't even know if it would be possible without a mess of Go's type system.

Otherwise I'm good.

**Comment by dkumor** [comment]
It is possible - I am currently grappling with a single one. Once that is done, I can create a special sub-object setting function
```go
duck.SetSubItem(val interface{}, element []interface{}, setto interface{}) (ok bool)
```

**Comment by dkumor** [comment]
The syntax is:
```go
duck.Set(val, toset interface{}, ...elem interface{})
```

The readme shows examples of usage.
Set will still not work in cases of most map types - but it does work with the most important case of `map[string]interface{}` which is what json marshals objects to.
